### ISSUE TITLE
Keeps crashing. What am I doing wrong? [Help needed]

### ISSUE THREAD

**Issue by alimir1** [FolioReader/FolioReaderKit#184] opened 2016-11-22 05:16 UTC
Thanks for this. Looks awesome; however, I'm trying to use this repo but with no success (first time using this). I'll donate if I get this issue fixed.

I have the following setup:

![screen shot 2016-11-21 at 9 10 14 pm](https://cloud.githubusercontent.com/assets/3302661/20511691/3721ca6a-b02f-11e6-929f-23ae2919b75a.png)

![screen shot 2016-11-21 at 9 10 22 pm](https://cloud.githubusercontent.com/assets/3302661/20511697/3f2ae7e6-b02f-11e6-8c10-286832fd97e8.png)

But when I run the app, I get the following message:

![screen shot 2016-11-21 at 9 14 05 pm](https://cloud.githubusercontent.com/assets/3302661/20511739/7fc77166-b02f-11e6-8aef-ae03a64394d8.png)

![screen shot 2016-11-21 at 9 14 19 pm](https://cloud.githubusercontent.com/assets/3302661/20511740/84b1edfa-b02f-11e6-93d5-882afe16acf4.png)

I don't think it's because of Epub file since I've tried numerous files... I also tried to add the code in viewDidLoad() but with no success.

When I set (removeEpub: true) the same thing happens

**Comment by valinaga** [comment] 2016-11-25 13:13
+1

**Comment by alimir1** [comment] 2016-11-25 16:24
That's strange because in viewDidLoad() of FolioReaderCenter() collectionView is assigned:

![screen shot 2016-11-25 at 8 22 59 am](https://cloud.githubusercontent.com/assets/3302661/20630862/880ea66c-b2e8-11e6-8873-defa4247531b.png)
![screen shot 2016-11-25 at 8 23 10 am](https://cloud.githubusercontent.com/assets/3302661/20630861/880355fa-b2e8-11e6-8cc4-e94ed4e7becd.png)

**Comment by valinaga** [comment] 2016-11-25 16:58
I tested it and viewDidLoad() of FolioReaderCenter() is never called.

**Comment by valinaga** [comment] 2016-11-25 17:12
It's stupid solution but you can add this
`                self.centerViewController.viewDidLoad()`
on top of this
`                self.centerViewController.reloadData()`
at line around 145 in
`FolioReaderContainer.swift`
It works for me but it's stupid indeed. :(

**Comment by alimir1** [comment] 2016-11-26 00:32
awesome valinaga! Maybe you can do a pull request.

i'm gonna donate!

**Comment by hebertialmeida** [comment] 2016-12-09 00:23
This is very strange guys, I can not simulate that behavior `viewDidLoad` of not getting called. How to reproduce this?

**Comment by hebertialmeida** [comment] 2018-02-14 15:36
This should be fixed already.

**Closed by hebertialmeida** 2018-02-14 15:36 UTC
Labels: awaiting reply, bug
