### ISSUE TITLE
Unable to integrate using carthage 

### ISSUE THREAD

**Issue by hassan-rafique** [FolioReader/FolioReaderKit#98] opened 2016-07-15 10:43 UTC
I am trying to add FolioReader using carthage but when I run 'carthage update' I get the following error and it stops building framework for FolioReaderKit.

> *** Building scheme "JSQWebViewController" in JSQWebViewController.xcworkspace
xcodebuild timed out while trying to read Demo.xcodeproj

**Comment by hebertialmeida** [comment] 2016-07-15 13:17
Hey @hassan-rafique 

We are aware about it, unfortunately the Carthage implementation is not working because of some dependencies. We are trying to fix this with on this branch:
https://github.com/FolioReader/FolioReaderKit/tree/fix/menuitem-dependencies

The carthage problem is fixed here, but the problem is that we have replaced the UIMenuItem-CXAImageSupport by MenuItemKit and it is not working properly, may we will have to rollback.

I think that for now the solution for this is to use Cocoapods integration.

**Comment by alexpopov** [comment] 2016-07-15 17:37
@hassan-rafique if we do end up doing the roll-back, I will try getting the old UIMenuItem library to compile with Carthage.

**Comment by hassan-rafique** [comment] 2016-07-16 05:27
Thanks for the update. I have used Cocoapods for now.

**Comment by MuffinWithJam** [comment] 2016-09-04 08:12
Any news about Carthage integration?

**Comment by hebertialmeida** [comment] 2016-09-06 13:46
For now please use Cocoapods, is the best and simple way to integrate. We have problem with dependencies, they are not building on Carthage.

**Comment by hebertialmeida** [comment] 2016-10-07 03:20
Fixed by 14282a71454476be74d1fcc3b2ce866c6a94205c

**Closed by hebertialmeida** 2016-10-07 03:20 UTC
Labels: bug
