### ISSUE TITLE
Book Search 

### ISSUE THREAD

**Issue by ali-zahedi** [FolioReader/FolioReaderKit#265] opened 2017-09-26 16:47 UTC
Can I ask you, have you plan for release book search ?
and can I Donate for this issue?

**Comment by hebertialmeida** [comment] 2018-01-12 20:05
I want to implement that, but I am really shot in time so at some point it will eventually be implemented, but I can't guarantee.

**Comment by hebertialmeida** [comment] 2018-01-12 20:06
I will close this as it is duplicate of #43

**Closed by hebertialmeida** 2018-01-12 20:06 UTC
Labels: feature request
