### ISSUE TITLE
Tap "Aa" button app crashed

### ISSUE THREAD

**Issue by Julyyq** [FolioReader/FolioReaderKit#215] opened 2017-03-06 10:08 UTC
Error: 
`assertion failed: Index at 3 is out of bounds: file /Users/Allen/o2/Pods/FolioReaderKit/Vendor/SMSegmentView/SMSegmentView.swift, line 240`

This error occurs with no 100%.

The problem seems be cause of the code in the `FolioReaderFontsMenu.swift`file:

    layoutDirection.selectSegmentAtIndex(scrollDirection?.rawValue ?? 0)

the rawValue sometimes returns wrong I guess , but I don't figure it out yet.

**Comment by Julyyq** [comment] 2017-04-07 03:38
Yes, it's reproducible on latest master version, I just fetch new master code and try it, app will crash on the following line in `SMSegmentView.swift` file as before:

![screen shot 2017-04-07 at 11 29 15](https://cloud.githubusercontent.com/assets/2620575/24784519/b623d01c-1b85-11e7-9c80-4eb7cb00a3de.png)

I try to figure out the problem, find that the line `layoutDirection.selectSegmentAtIndex(scrollDirection?.rawValue ?? 0)` in the `FolioReaderFontsMenu.swift` file, the `scrollDirection?.rawValue` is incorrect, but I don't know why. I comment this line and app won't crash any more.

BTW, my init code:

    -(void)showReader {
        NSString *filePath = self.article.epub_local_path;
        FolioReaderConfig *config = [FolioReaderConfig new];
        [config setNightModeBackground:[UIColor colorWithRed:29.0f/255.0f green:29.0f/255.0f blue:31.0f/255.0f alpha:1.0f]];
        [config setShouldHideNavigationOnTap:true];
        [config setEnableTTS:false];
        [config setAllowSharing:false];
        [config setTintColor:[UIColor colorWithRed:29.0f/255.0f green:133.0f/255.0f blue:240.0f/255.0f alpha:1.0f]];
        [FolioReader presentReaderWithParentViewController:self withEpubPath: filePath andConfig:config shouldRemoveEpub:true animated:true];
    }

**Comment by SalarDastan** [comment] 2017-04-07 19:33
same here
![screen shot 2017-04-08 at 12 01 55 am](https://cloud.githubusercontent.com/assets/23551399/24816623/b6775a3e-1bee-11e7-8ab1-1ab8e5f49717.png)

`@IBAction func readBookPressed(_ sender: UIButton) {
        let config = FolioReaderConfig()
        let bookPath = Bundle.main.path(forResource: "nimtaj", ofType: "epub")
        FolioReader.presentReader(parentViewController: self, withEpubPath: bookPath!, andConfig: config)
    }`

**Comment by iMemento** [comment] 2017-04-08 08:40
Same here when I pressed Aa Button, app crashed. I think the reason is that I set TTS enable false.

**Comment by mitulmarsonia** [comment] 2017-04-08 18:56
I'm also getting crashed. Can you please fix it.
Thank you.

**Comment by mitulmarsonia** [comment] 2017-04-08 19:13
I have find out solution:- 

Just go to **SMSegmentView.swift** and replace below function.

 

`    func selectSegmentAtIndex(_ index: Int) {
//    assert(index >= 0 && index < self.segments.count, "Index at \(index) is out of bounds")
        if index>1
        {
            self.selectSegment(self.segments[1])
        }else{
            self.selectSegment(self.segments[index])
        }
        
    }`

**Comment by twototwoto** [comment] 2017-04-13 03:42
**when I tap the Aa, I encounted the same problem.**

**After I pod it in my app, while run it in my real iPad，**
![real ipad](https://cloud.githubusercontent.com/assets/18694645/24989021/1f103010-203c-11e7-9232-1a8352810919.png)

**when I run it in simulator,**
![simulatorrun](https://cloud.githubusercontent.com/assets/18694645/24989304/32598fca-203e-11e7-9086-f2de78a10831.png)

**Comment by ianyh** [comment] 2017-05-01 17:33
I ran into this the other day. I think the problem is something going wrong between versions. I had `FolioReader.currentScrollDirection == 3`, which maps to `.defaultVertical`. The check here

https://github.com/FolioReader/FolioReaderKit/blob/6bfb0550b4e5272b73f8200901c43c14e441a45a/Source/FolioReaderFontsMenu.swift#L242

does not trigger because the config also has `.defaultVertical`. There's only two segments in the segment view, though, so it tries to select the third and crashes. It seems like `.defaultVertical` should always be remapped to `.vertical` before using it access the current segment.

**Comment by twototwoto** [comment] 2017-05-11 09:09
I do not know what is wrong. Maybe we can change the code as follows . Maybe it is bad way,while if we are in a hurry, I think we can change it to run it normally
![Uploading changeIt.png…]()
![Uploading runNormally.png…]()

**Comment by ianyh** [comment] 2017-05-11 15:37
I just opened a quick PR that fixes and hopefully better illustrates the issue. #238

**Comment by nicoachkasov** [comment] 2017-05-27 21:46
I don't know... Just for it to work ASAP, I just commented out the assertion and used the 0 index.
<img width="765" alt="screen shot 2017-05-28 at 12 45 19 am" src="https://cloud.githubusercontent.com/assets/6266153/26524543/fa1c1000-433e-11e7-8045-ea5219e5bfbb.png">

**Comment by hebertialmeida** [comment] 2017-05-29 15:02
This is fixed on @ianyh PR #238 thanks guys!!!

**Closed by hebertialmeida** 2017-05-29 15:02 UTC
Labels: awaiting reply
